// GENERATED by scripts/sync-upstream-baseline.mjs — do not edit by hand.
//
// Offline snapshot of the atomic-chat-conf backend manifest. `fetchRemoteBackends`
// parses it as a last resort when every network transport fails (ATO-243), so it
// deliberately carries real tags and backend ids: the download path keeps
// working, it is just older than the live manifest until the network recovers.
//
// Regenerate with `make sync-upstream-baseline` after the manifest moves. The
// tag here is NOT a pin — a live manifest on a newer tag is followed as-is.
import type { UpstreamManifest } from './backend'

export const BUNDLED_MANIFEST_BASELINE: UpstreamManifest = {
  tag_name: 'b11463',
  download_base: 'https://github.com/AtomicBot-ai/atomic-chat-conf/releases/download',
  assets: [
    { name: 'llama-b11463-bin-macos-arm64.tar.gz', sha256: '165ffa2049ac5cd706978ff64f6cba7a8ab1d8c343e8124c81d17a589a7a14ab', size: 12087659 },
    { name: 'llama-b11463-bin-ubuntu-vulkan-x64.tar.gz', sha256: '5d428312d97e4c25eb28277416de935a76ca80bf7ede6b418d43a2b10c0336cd', size: 31678494 },
    { name: 'llama-b11463-bin-ubuntu-x64.tar.gz', sha256: 'c7d63a3dfd1fe93a679b4bcd981dacb9153e2509a21bb912b9a01fc28a8447f5', size: 17732486 },
    { name: 'llama-b11463-bin-win-cpu-arm64.zip', sha256: '1dc49d7802ef3a5a9a9fca6c3fecbcb61a8874ab1ac6d50bdf4bba9bf373e9a9', size: 12552504 },
    { name: 'llama-b11463-bin-win-cpu-x64.zip', sha256: '20c85707d83aeac712bfcdfd6c9a1f41c0c837054e64f888df1bf38650fe3096', size: 19827051 },
    { name: 'llama-b11463-bin-win-cuda-12.4-x64.zip', sha256: '46a4534331a1c20bb3053b90c92d41efc81b86c21e1c315c5e32e069cd8280b7', size: 264348410 },
    { name: 'llama-b11463-bin-win-cuda-13.4-arm64.zip', sha256: 'a92d32bf1ccffef0586ef0a294801eb711d55dadd67df303ec28f92004372050', size: 145323516 },
    { name: 'llama-b11463-bin-win-cuda-13.4-x64.zip', sha256: '63f727adf8d26c8513e365ad4ce17bc2e541b634e66dc0fc5e8442d0d2b268ef', size: 152957959 },
    { name: 'llama-b11463-bin-win-opencl-adreno-arm64.zip', sha256: '2c02936be66558bb9aa410cde9378cee7586d423d5845829f7d78f5f90aed66f', size: 13111354 },
    { name: 'llama-b11463-bin-win-rocm-10.0-x64.zip', sha256: '60bbf7f1fdf035a80e7d3495b45a673e2746b5270cca82112dda8116a62386f5', size: 256849434 },
    { name: 'llama-b11463-bin-win-vulkan-x64.zip', sha256: '12ec6aede90b03abf0115027d990c2f99e320bc66df1117688aae5febb640ef8', size: 33198042 },
    { name: 'cudart-llama-bin-win-cuda-12.4-x64.zip' },
    { name: 'cudart-llama-bin-win-cuda-13.4-arm64.zip' },
    { name: 'cudart-llama-bin-win-cuda-13.4-x64.zip' },
  ],
}
