#!/usr/bin/env python3
"""Generate skill distributions, the context pack, and Part 4's bundled templates."""
import argparse
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
expected = {}
for src in sorted((root / 'workflow/skills').rglob('*')):
    if src.is_file():
        for dest in ['.agents/skills', '.claude/skills', 'templates/.agents/skills', 'templates/.claude/skills']:
            expected[root / dest / src.relative_to(root / 'workflow/skills')] = src.read_bytes()
setup_files = [root / 'templates' / n for n in ['AGENTS.md', 'MEMORY.md', 'REVIEW-CHECKLIST.md']] + sorted((root / 'templates/agent_docs').glob('*.md'))
pack = ['# Vibe Workflow chat context pack\n\nGenerated by scripts/sync-skills.py from templates/.\n\nOptional standalone copy of the core templates already bundled in Part 4. Use with the Part 4 instructions, your PRD, and your Tech Design.\n\nThese are templates to fill, not evidence that setup or behavior has been checked.\n']
bundled = ['<!-- Generated by scripts/sync-skills.py from templates/. -->']
for src in setup_files:
    content = src.read_text()
    name = str(src.relative_to(root / 'templates'))
    pack.append('\n## File: ' + str(src.relative_to(root / 'templates')) + '\n\n' + src.read_text())
    # Longer outer fences preserve any fenced examples inside a source template.
    fence = chr(96) * max(4, 1 + max((len(m.group()) for m in re.finditer(chr(96) + '+', content)), default=0))
    bundled.append('\n### File: ' + name + '\n\n' + fence + 'markdown\n' + content.rstrip() + '\n' + fence)
expected[root / 'docs/context-pack.md'] = '\n'.join(pack).encode()
part4 = root / 'part4-notes-for-agent.md'
part4_text = part4.read_text()
begin = '<!-- BEGIN BUNDLED SETUP TEMPLATES -->'
end = '<!-- END BUNDLED SETUP TEMPLATES -->'
if part4_text.count(begin) != 1 or part4_text.count(end) != 1:
    raise SystemExit('Part 4 must contain exactly one bundled-template marker pair.')
pattern = re.compile(re.escape(begin) + r'.*?' + re.escape(end), re.DOTALL)
if not pattern.search(part4_text):
    raise SystemExit('Part 4 bundled-template markers are out of order.')
replacement = begin + '\n' + '\n'.join(bundled) + '\n' + end
expected[part4] = pattern.sub(lambda _: replacement, part4_text).encode()
errors = []
for path, content in expected.items():
    if args.check:
        if not path.exists() or path.read_bytes() != content:
            errors.append(str(path.relative_to(root)))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
for dest in ['.agents/skills', '.claude/skills', 'templates/.agents/skills', 'templates/.claude/skills']:
    for path in (root / dest).rglob('*'):
        if path.is_file() and path not in expected:
            errors.append('Unexpected distribution file: ' + str(path.relative_to(root)))
if errors:
    raise SystemExit('Generated workflow files out of sync:\n' + '\n'.join(errors))
print('Skill distributions, context pack, and Part 4 templates ' + ('checked' if args.check else 'generated'))
