"""Pushes the same grounded API reference Docs shows in the dashboard into
the customer's own repo, for installations that opted in (see
docs_repo_commit_settings). Delivered as a single rolling PR rather than
direct commits to the default branch - mirrors Dependabot's model, which
matters here because a customer's branch protection (required status
checks, no direct pushes) would otherwise reject a bot commit outright.

The branch (DOCS_COMMIT_BRANCH) is bot-owned and reset to "latest default
branch + our one file" on every run, so it never accumulates drift or shows
an unrelated diff - a customer opening the PR always sees exactly the
reference change, nothing else.
"""

import hashlib
import logging

from aletheore.docs_reference import build_combined_reference
from scan_worker.github_api import (
    ensure_branch_at,
    ensure_docs_pull_request,
    fetch_default_branch_and_head_sha,
    upsert_repo_file,
)

logger = logging.getLogger(__name__)

DOCS_COMMIT_BRANCH = "aletheore/docs-update"
DOCS_COMMIT_PATH = ".aletheore/docs/API.md"
DOCS_COMMIT_MESSAGE = "docs: update Aletheore-generated API reference"
DOCS_COMMIT_PR_TITLE = "docs: update Aletheore-generated API reference"
DOCS_COMMIT_PR_BODY = (
    "Auto-generated by [Aletheore](https://aletheore.com) Docs from the current evidence-grounded "
    "API reference (`.aletheore/docs/API.md`). This PR is updated in place whenever the reference "
    "changes rather than a new one opening each time - safe to leave open and merge whenever convenient."
)


def sync_docs_to_repo(
    client,
    token: str,
    repo_full_name: str,
    modules: dict[str, str],
    settings: dict | None,
    bot_login: str,
    evidence: dict | None = None,
) -> tuple[str, int] | None:
    """Returns (content_hash, pr_number) to persist via
    record_docs_repo_commit when a push happened, or None when nothing
    changed (not opted in, or content identical to the last push).

    bot_login (e.g. "aletheore[bot]") is used to verify we actually own
    DOCS_COMMIT_BRANCH before force-pushing over it - see ensure_branch_at.

    evidence, when given, adds the "API Endpoints"/"Database Schema"
    overview sections build_combined_reference supports - see its own
    docstring. Omitted (the default) reproduces the exact prior output."""
    if settings is None or not settings.get("enabled"):
        return None

    markdown = build_combined_reference(modules, repo_full_name, evidence)
    content_hash = hashlib.sha256(markdown.encode("utf-8")).hexdigest()
    if settings.get("last_content_hash") == content_hash:
        return None

    default_branch, base_sha = fetch_default_branch_and_head_sha(client, token, repo_full_name)
    ensure_branch_at(client, token, repo_full_name, DOCS_COMMIT_BRANCH, base_sha, bot_login)
    upsert_repo_file(
        client, token, repo_full_name, DOCS_COMMIT_PATH, DOCS_COMMIT_BRANCH, markdown, DOCS_COMMIT_MESSAGE,
    )
    pr_number = ensure_docs_pull_request(
        client, token, repo_full_name, DOCS_COMMIT_BRANCH, default_branch,
        DOCS_COMMIT_PR_TITLE, DOCS_COMMIT_PR_BODY,
    )
    return content_hash, pr_number
